import { useState } from "react";
import { Inter } from "@next/font/google";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Search from "../components/Search";
import Weather from "../components/Weather";
import Spinner from "../components/Spinner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [snackbarMessage, setSnackbarMessage] = useState("");
  const [weather, setWeather] = useState({});
  const [city, setCity] = useState("");
  const [languageChange, setLanguageChange] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  let language = "sp";
  let langSB = "";
  let placeholder = "Buscar ciudad";
  let weatherIn = "Clima en";
  let feelsLike = "Se siente de";
  let humidity = "Humedad";
  let wind = "Viento";
  let errorMessage = "No se pudo obtener el clima. Intenta de nuevo.";

  const handleLanguageChange = () => {
    setLanguageChange(!languageChange);
    setSnackbarMessage(null);
    setIsOpen(true);
  };

  if (!languageChange) {
    language = "sp";
    langSB = "Español seleccionado";
    placeholder = "Buscar ciudad";
    weatherIn = "Clima en ";
    feelsLike = "Se siente de";
    humidity = "Humedad";
    wind = "Viento";
    errorMessage = "No se pudo obtener el clima. Intenta de nuevo.";
  } else {
    language = "en";
    langSB = "English selected";
    placeholder = "Search city";
    weatherIn = "Weather in ";
    feelsLike = "Feels like";
    humidity = "Humidity";
    wind = "Wind";
    errorMessage = null;
  }

  let labels = {
    placeholder: placeholder,
    snackbarMessage: snackbarMessage,
    langSB: langSB,
  };

  const handleToClose = (event, reason) => {
    if ("clickaway" == reason) return;
    setIsOpen(false);
  };

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&lang=${language}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setIsLoading(true);
    axios
      .get(url)
      .then((response) => {
        setWeather(response.data);
      })
      .catch((error) => {
        const message =
          errorMessage ||
          error.response?.data?.message ||
          "Something went wrong. Please try again.";
        setSnackbarMessage(message);
        setIsOpen(true);
      })
      .finally(() => {
        setIsLoading(false);
      });
    setCity("");
  };
  return (
    <div>
      <Head>
        <title>WeatherNext</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/weatherFavicon.ico' />
      </Head>

      {/* Overlay */}
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/60 z-[1]' />

      {/* Background Image */}
      <Image
        alt='background'
        src='https://images.pexels.com/photos/296559/pexels-photo-296559.jpeg'
        layout='fill'
        className='object-cover'
      />

      {/* Search */}
      <Search
        isOpen={isOpen}
        labels={labels}
        {...{ fetchWeather }}
        {...{ setCity }}
        {...{ handleLanguageChange }}
        {...{ handleToClose }}
      />
      {/* Search end */}

      {isLoading ? (
        <Spinner />
      ) : (
        /* Weather */
        weather.main && (
          <Weather
            data={weather}
            weatherIn={weatherIn}
            feelsLike={feelsLike}
            humidity={humidity}
            wind={wind}
          />
        )
        /* Weather end */
      )}
    </div>
  );
}
